apiVersion: v1
kind: Pod
metadata:
  name: backend-pod
  namespace: ndl
spec:
  containers:
  - name: backend-container
    image: my-backend-image
    livenessProbe:
      tcpSocket:
        port: 8080
      initialDelaySeconds: 15
      periodSeconds: 10
    readinessProbe:
      exec:
        command:
        - /bin/sh
        - -c
        - curl -s -o /dev/null http://database-service.ndl.svc.cluster.local:8085/healthcheck && exit 0 || exit 1
      initialDelaySeconds: 20
      periodSeconds: 10
