apiVersion: v1
kind: Secret
metadata:
  name: my-tls-secret
type: kubernetes.io/tls
data:
  tls.crt: <my-base64-encoded-certificate>
  tls.key: <my-base64-encoded-private-key>

# Generate private key
# openssl genpkey -algorithm RSA -out my-private-key.key

# Generate a certificate signing request
# openssl req -new -key my-private-key.key -out my-certificate-signing-request.csr

# Generate a self-signed certificate
# openssl x509 -req -days 365 -in my-certificate-signing-request.csr -signkey my-private-key.key -out my-certificate.crt
