apiVersion: apps/v1
kind: Deployment
metadata:
  name: sample-app-2
  namespace: my-space
spec:
  replicas: 10
  selector:
    matchLabels:
      app: sample-app
  template:
    metadata:
      labels:
        app: sample-app
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: kubernetes.io/hostname
                    operator: In
                    values:
                      - worker1
      containers:
        - name: nginx-container
          image: nginx:1.21.6
          ports:
            - containerPort: 80
