# Kubernetes Port Forwarding

# Kubernetes port forwarding is a mechanism that allows us to access services running inside a Kubernetes cluster from our local machine or another system outside the cluster. It's particularly useful for debugging, accessing databases, or interacting with specific services during development or testing phases without exposing them to the broader network.

# Targeting Specific Containers

## kubectl port-forward <pod-name> <local-port>:<pod-port> --container <container-name>

# Accessing Services Using Selectors

## kubectl port-forward service/<service-name> <local-port>:<service-port>

# Sample Command

## kubectl port-forward mypod 8080:80
