apiVersion: batch/v1
kind: Job
metadata:
  name: init-container-example
spec:
  template:
    spec:
      containers:
      - name: main-container
        image: alpine:latest
        command: ['sh', '-c', 'echo "Current time in main container:" && date']
        ports:
        - containerPort: 80
      initContainers:
      - name: init-container
        image: alpine:latest
        command: ['sh', '-c', 'echo "Current time in init container:" && date; sleep 15']
      restartPolicy: Never
