apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: my-statefulset-with-toleration
  namespace: my-namespace
spec:
  serviceName: "my-service-with-toleration"
  replicas: 3
  selector:
    matchLabels:
      app: my-app-with-toleration
  template:
    metadata:
      labels:
        app: my-app-with-toleration
    spec:
      containers:
      - name: my-container
        image: nginx
        ports:
        - containerPort: 80
      tolerations:
      - key: "avoid"
        operator: "Equal"
        value: "true"
        effect: "NoSchedule"
  volumeClaimTemplates:
  - metadata:
      name: my-persistent-volume-claim-with-toleration
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
